before_commands:
    - "composer install --prefer-source"

tools:
    external_code_coverage: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["/tests/", "vendor"]
    php_cs_fixer:
        enabled: false
        config:
            level: all
        filter:
            paths: ["src/*", "/tests/*"]
    php_loc:
        enabled: true
    php_mess_detector:
        enabled: true
        filter:
            paths: ["/tests/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["/tests/", "vendor"]
    php_analyzer:
        filter:
            paths: ["src/*", "/tests/*"]
    sensiolabs_security_checker: true